# This file was generated by GoReleaser. DO NOT EDIT.
cask "spelunk" do
  version "2.2.1"

  on_macos do
    on_arm do
      sha256 "c3ee29a88f028ce272c808e56a417a0e2317267b466c605e71926ea256a17ac9"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_darwin_arm64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.1_darwin_arm64/spelunk", "spelunk"
    end
    on_intel do
      sha256 "c72f6ed4a25ce7e3f52e38aa995bd6fed31bf8556c14d047512d422be01ab6ac"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_darwin_amd64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.1_darwin_amd64/spelunk", "spelunk"
    end
  end
  on_linux do
    on_arm do
      sha256 "cdcf6eddcf843e5f9aa16abcfec7b27302a9dae0c39c72fdc4b0ef0634837d94"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_linux_arm64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.1_linux_arm64/spelunk", "spelunk"
    end
    on_intel do
      sha256 "19aceeb7e79e5e20b1c1bda34651642f42acbee5b561a1ce144793b70181bf12"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_linux_amd64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.1_linux_amd64/spelunk", "spelunk"
    end
  end

  name "spelunk"
  desc "Retrieve secrets from Kubernetes, Vault, AWS, GCP, Azure, 1Password and more"
  homepage "https://github.com/detro/spelunk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spelunk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spelunk"]
    end

    {
      "bash" => "#{HOMEBREW_PREFIX}/etc/bash_completion.d/spelunk",
      "zsh"  => "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_spelunk",
      "fish" => "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/spelunk.fish",
    }.each do |shell, target|
      completion = system_command("#{staged_path}/spelunk", args: ["completion", "-c", shell]).stdout
      FileUtils.mkdir_p File.dirname(target)
      File.write(target, completion)
    end
  end

  uninstall delete: [
    "#{HOMEBREW_PREFIX}/etc/bash_completion.d/spelunk",
    "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/spelunk.fish",
    "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_spelunk",
  ]

  zap delete: [
    "#{HOMEBREW_PREFIX}/etc/bash_completion.d/spelunk",
    "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/spelunk.fish",
    "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_spelunk",
  ]
end
