# This file was generated by GoReleaser. DO NOT EDIT.
cask "spelunk" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "ad110d3eb1454f9e7404831b1fbde47605e2a18ad5752896dde23dd80ffd4adf"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_darwin_arm64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.0_darwin_arm64/spelunk", "spelunk"
    end
    on_intel do
      sha256 "7d714110a34c31e63dff024c398d00f9d01a929ab605e1911a832d3307778624"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_darwin_amd64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.0_darwin_amd64/spelunk", "spelunk"
    end
  end
  on_linux do
    on_arm do
      sha256 "89d13d2175dd27b81e3915ae9eadf953dffaa046b43e5e7c937428593a08d060"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_linux_arm64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.0_linux_arm64/spelunk", "spelunk"
    end
    on_intel do
      sha256 "8c783067cd11f408055aafe0ba952adfb30e867304ca8a04f682aa856884ad66"
      url "https://github.com/detro/spelunk/releases/download/v#{version}/spelunk_#{version}_linux_amd64.tgz",
          verified: "github.com/detro/spelunk"
      rename "spelunk_2.2.0_linux_amd64/spelunk", "spelunk"
    end
  end

  name "spelunk"
  desc "Retrieve secrets from Kubernetes, Vault, AWS, GCP, Azure, 1Password and more"
  homepage "https://github.com/detro/spelunk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spelunk"
  generate_completions_from_executable "spelunk", "completion", "-c",
                                       base_name: "spelunk",
                                       shells:    [:bash, :zsh, :fish]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spelunk"]
    end
  end

  # No zap stanza required
end
